name: Release Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build:
    uses: ./github/workflows/build.yml  # Reusable build workflow
    with:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifact
          path: dist/Windows/*.exe

      - name: Upload macOS Artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifact
          path: dist/macOS/*.dmg

      - name: Upload Linux Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifact
          path: dist/Linux/*.AppImage