name: Release Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Build on three different OSes

    runs-on: ${{ matrix.os }} # Runs the job on the OS from the matrix

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use Node.js version 18, adjust as needed

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Rebuild any native modules (e.g., node-pty)
      - name: Rebuild native modules
        run: npm run rebuild

      # Build the Electron app for the current OS
      - name: Build Electron app
        run: npm run build

      # Upload Windows Artifact (.exe)
      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: windows-artifact
          path: dist/*.exe

      # Upload macOS Artifact (.dmg)
      - name: Upload macOS Artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: macos-artifact
          path: dist/*.dmg

      # Upload Linux Artifact (.AppImage)
      - name: Upload Linux Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: linux-artifact
          path: dist/*.AppImage